### ISSUE TITLE
Crash on setChatDraftMessage

### ISSUE THREAD

**Issue by ggoraa** [Swiftgram/TDLibKit#17]
Crash log:

`
Thread 20: Fatal error: 'try!' expression unexpectedly raised an error: Swift.EncodingError.invalidValue(TDLibKit.DTO<TDLibKit.SetChatDraftMessage>, Swift.EncodingError.Context(codingPath: [], debugDescription: "Unable to encode the given top-level value to JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3852 "The string 0x60400015f490 failed to convert to UTF8" UserInfo={NSDebugDescription=The string 0x60400015f490 failed to convert to UTF8})))
`
![image](https://user-images.githubusercontent.com/61655029/188393550-7c50995c-9aa3-4039-a960-6c29b02b3364.png)
![image](https://user-images.githubusercontent.com/61655029/188393577-09c40d35-7b94-48a8-ab9b-3a782135064b.png)
![image](https://user-images.githubusercontent.com/61655029/188393609-5e3837be-e658-469f-983e-13481a1132cb.png)

**Comment by cyberbarker** [comment]
Emojis work great. Try something like below

```
    _ = try? await ServiceLayer.instance().telegramService.api.setChatDraftMessage(
                    chatId: chat.id,
                    draftMessage: .init(
                        date: Int(Date().timeIntervalSince1970),
                        inputMessageText: .inputMessageText(.init(
                            clearDraft: false,
                            disableWebPagePreview: false,
                            text: .init(entities: [], text: messageText))
                        ),
                        replyToMessageId: 0
                    ), messageThreadId: 0
                )
```

**Comment by Kylmakalle** [comment]
@ggoraa said that the crash was a client-specific issue due to utf-16 emoji representation

**Comment by Kylmakalle** [comment]
`TextEntity` accepts only utf-16 representation

https://t.me/moc_discussion/6708
