### ISSUE TITLE
Library version for Mac?

### ISSUE THREAD

**Issue by riley-usagi** [Swiftgram/TDLibKit#2]
`/.../SourcePackages/artifacts/TDLibFramework/TDLibFramework.xcframework:1:1: While building for Mac Catalyst, no library for this platform was found in '/.../Library/Developer/Xcode/DerivedData/ProjectName-corvnrfobakfdwcuppirqinfekkq/SourcePackages/artifacts/TDLibFramework/TDLibFramework.xcframework'.`

**Comment by Kylmakalle** [comment]
Caused by https://github.com/Swiftgram/TDLibFramework/issues/62
