### ISSUE TITLE
Linux executables support

### ISSUE THREAD

**Issue by Maxim-Lanskoy** [Swiftgram/TDLibKit#20]
I'm sorry if my question is not formulated well, but I'm trying to use your kit in a linux swift executable.

When I repeat the same steps as on the macOS (using SPM), I'm getting  "`error: no such module 'TDLibFramework'`" errors that come from `TDLibKit` related files.

<img width="458" alt="Screenshot 2022-11-19 at 23 19 06" src="https://user-images.githubusercontent.com/16775231/202871991-79aa3d25-a613-4224-8459-8eb91dc023c4.png">

Is it even possible to use in such a scenario and what can I do to try fix this problem? 
Thanks in advance for your time!

**Comment by Maxim-Lanskoy** [comment]
Here is minimal example of reproducing this issue:

`git clone https://github.com/Maxim-Lanskoy/TDLibKit-Linux-Example`
`cd TDLibKit-Linux-Example/`
`swift package resolve && swift run`

Also, if your linux does not have `unzip`, there will be next error:
`could not find executable for 'unzip'`
that can be fixed with `sudo apt install unzip`.

**Comment by Kylmakalle** [comment]
> TDLibKit... Available on iOS, macOS, watchOS and tvOS.

Underneath [TDLibFramework](https://github.com/Swiftgram/TDLibFramework) does not target any linux platforms.

**Comment by Kylmakalle** [comment]
You will need to build a library for your system. Then provide a wrapper for Swift that will expose TDLib's [JSON interface](https://github.com/tdlib/td#using-from-other-programming-languages). Not sure if the second thing is possible in terms of SPM.
