### ISSUE TITLE
Coding Keys error

### ISSUE THREAD

**Issue by ibengeu** [Swiftgram/TDLibKit#25]
Hello @Kylmakalle, I am currently receiving this type of error, what does it signify and how I can I fix?

```
keyNotFound(CodingKeys(stringValue: "isPersonal", intValue: nil), Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "user", intValue: nil), CodingKeys(stringValue: "profilePhoto", intValue: nil)], debugDescription: "No value associated with key CodingKeys(stringValue: \"isPersonal\", intValue: nil) (\"isPersonal\"), converted to is_personal.", underlyingError: nil)
```

Update:
In the process of debugging this issue, I noticed a couple of keys do not match the key names in the class documentation. eg.

- autoDeleteIn type is  _written as_  ttl in the telegram chat/message class 

- IsPersonal of type Photo or profilePhoto has no corresponding keys  within the photo class.

So there seems to be a mismatch

**Comment by ibengeu** [comment]
Also for some reason unknown, the "updateNewChat", "updateNewLastMessage" and "updateChatTitle" or updates that deals with chats are not triggered but I can see it being sent by the TDJSON log

**Comment by ibengeu** [comment]
updating the keys manually to the class representation resolves this issue

**Comment by Kylmakalle** [comment]
@ibengeu I see that you're talking about keys that were a part of recent functionality.

Can you please specify your full TDLibKit version?

**Comment by ibengeu** [comment]
1.2.1-tdlib-1.8.10-19cde80f

 I see some of the affected keys within the latest release (eg. autoDeleteIn)

**Comment by Kylmakalle** [comment]
As I can see, fields such as `isPersonal` was first seen in tdlib `1.8.10`. 
https://github.com/Swiftgram/TDLibKit/commit/69318a8542d5af31ee477a2ee7996651feaf9cf9#diff-e2cc257062d4381fb6313a3c5cf4d4d501556916eae31309c9fd23830b5429a7R22-R24

Please double-check that you're using the most recent version of TDLibKit to ensure support for such fields. 

> 1.2.1-tdlib-1.8.10-19cde80f

I assume you've updated to the latest version and do not have any further issues with TDLibKit.
