### ISSUE TITLE
Release build configuration gets stuck and never ends

### ISSUE THREAD

**Issue by levochkaa** [Swiftgram/TDLibKit#31]
When trying to build a project with TDLibKit added, using Release build configuration, the build never ends.
But when trying to build using Debug build configuration everything is OK.
I suppose, providing the compile command won't give any info, really, but here is a screenshot:
![telegram-cloud-photo-size-2-5359409872015313623-x](https://user-images.githubusercontent.com/62802017/235253768-3331a856-ad99-409f-9a2b-ecfd51ca1e1e.jpg)

As I remember, I was able to build Release, when generating .ipa file for [BetterTG v2 release](https://github.com/levochkaa/BetterTG/releases/tag/v2). So, in the beginning of December 2022 everything was working.
Now I've tried some commits after that and none of them built.

I've created a [minimal reproducible example](https://github.com/levochkaa/TestTDLibKit) for you to check out. It's just a fresh created SwiftUI app with latest TDLibKit package added.

I'm not sure how `xcodebuild` works and what the issue is, but I have some thoughts:
- XCode is building Release, combining all files to one compile command and is struggling to do that, whereas Debug is built using different compile commands.
- The solution might be in separating TDLibKit into several packages, that would also help in [this issue](https://github.com/Swiftgram/TDLibKit/issues/19)
- Not using `xcodebuild`?

**Comment by levochkaa** [comment]
Tried working TDLibKit and building Release of the package - same

**Comment by levochkaa** [comment]
Removed redundant struct and enum initializers - same

**Comment by levochkaa** [comment]
I was just playing with the generator and made some (i think) helpful changes
Added [Hashable for structs and enums and Identifiable](https://github.com/Swiftgram/TDLibKit/issues/26) for structs, lol

Removed redundant code (see my prev message)

I can make a Pull Request with these changes (might be 2-3 PR's). Are you interested in that @Kylmakalle or you know about this and don't want to implement, because of..?

**Comment by Kylmakalle** [comment]
@levochkaa I would love to see https://github.com/Swiftgram/TDLibKit/issues/26 to be implemented.

Identifiable - AFAIK some TDLib objects may have non-unique properties.

Hashable - keep an eye on TdInt64 and similar types

**Comment by Kylmakalle** [comment]
> The solution might be in separating TDLibKit into several packages, that would also help in this issue

Highly likely. The issue you described sounds like an overwhelming amount of optimizations done for Release builds. Can you please try to tweak  Swift optimizations in the Build settings?

**Comment by levochkaa** [comment]
> > The solution might be in separating TDLibKit into several packages, that would also help in this issue
> 
> Highly likely. The issue you described sounds like an overwhelming amount of optimizations done for Release builds. Can you please try to tweak Swift optimizations in the Build settings?

Tried tweaking Swift optimizations - nothing helped.
May be we should tweak optimizations directly in the package? somehow

**Comment by zintus** [comment]
This helps https://github.com/Swiftgram/TDLibKit/commit/208c9c494dd8d5ef1d78c284067c58c7cc801a51
Seems to be a swift compiler regression

**Comment by Kylmakalle** [comment]
@zintus thank you for the tip. It looks like my assumptions were not wrong, and we're still partially affected by something from issue https://github.com/Swiftgram/TDLibKit/issues/7

I'll leave this issue open and push the workaround to the main branch.

**Comment by levochkaa** [comment]
@zintus Thanks for the workaround!

I've just never worked with SPM packages and didn't know how to change such things😅

**Comment by Kylmakalle** [comment]
I've poked around a little with the provided example on my M1 Pro.

Xcode 14.1: ~165 seconds
Xcode 14.2: ~165 seconds
Xcode 14.3 beta 1: stuck
Xcode 14.3.1: stuck
Xcode 15 beta 5: stuck

Looks like the issue is in bumped Swift version from `Swift 5.7.2 (5.7.2.135.5)` to `Swift 5.8 (5.8.0.117.11)`

**Comment by Kylmakalle** [comment]
Trying to debug swift internals with

```swift
.unsafeFlags([
                "-driver-time-compilation",
                "-Xfrontend",
                "-debug-time-function-bodies",
                "-Xfrontend",
                "-debug-time-expression-type-checking",
                "-Xfrontend",
                "-warn-long-function-bodies=80",
                "-Xfrontend",
                "-warn-long-expression-type-checking=80"
            ])
```

**Comment by Kylmakalle** [comment]
With Custom toolchain, Swift development [snapshot 24.08.2023](https://download.swift.org/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2023-08-24-a/swift-DEVELOPMENT-SNAPSHOT-2023-08-24-a-osx.pkg) I was able to build under Xcode 14.3.1

**Comment by levochkaa** [comment]
I've checked on M2 Max on Xcode 15 beta 7 on the latest main branch commit atm: f912fb3, 1.5.0-tdlib-1.8.16-470c36ce tag
Library build time is ~66 seconds.
My telegram client build time is ~147 seconds.

**Comment by Kylmakalle** [comment]
@levochkaa can you please confirm the timings for **Archive**, not **Build**? Archive uses Release optimizations, while Build is for debugging.

**Comment by Kylmakalle** [comment]
**Good news**. We now have a less harsh way to unblock the release builds and maintain some optimizations to the final program.


I've been digging into the issue for two days straight. Mostly trying to rewrite the parser/generator inspiring with Telegram X Android and it's [abstract types](https://github.com/TGX-Android/tdlib/blob/main/src/main/java/org/drinkless/tdlib/TdApi.java), but the result were not convenient enough and additional type-hints + file structure changes were unable to speedup the build. 
Later, I was trying to find the coincidence in Xcode version changes. So I've stumbled upon the issue https://github.com/apple/swift/issues/58851 and was wondering how to get the same backtrace of a swift compiler. I've found that there's a [Wikipedia](https://en.wikipedia.org/wiki/Xcode) page with listed dependencies versions. `llvm` bump from 14.0.0 to 15.0.0 was interesting, but now I felt I need the backtrace anyway.

It turned out we could use the Instruments.app and attach it to the running `swift-frontend`. Here I was trying to find anything interesting.

I've scoped the issue to the `llvm::SLPVectorizerPass::run`
<details><summary>Backtrace from Xcode 14.3+</summary>

```
2442076	swift-frontend (61312)	
747277	  0x18f0b7	
747277	thread_start	
747277	_pthread_start	
747277	(anonymous namespace)::LLVMCodeGenThreads::runThread(void*)	
747277	(anonymous namespace)::LLVMCodeGenThreads::Thread::run()	
747277	swift::performLLVM(swift::IRGenOptions const&, swift::DiagnosticEngine&, llvm::sys::SmartMutex<false>*, llvm::GlobalVariable*, llvm::Module*, llvm::TargetMachine*, llvm::StringRef, swift::UnifiedStatsReporter*)	
745686	swift::performLLVMOptimizations(swift::IRGenOptions const&, llvm::Module*, llvm::TargetMachine*)	
745682	llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&)	
739675	llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&)	
739638	llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&)	
736376	llvm::SLPVectorizerPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&)	
736376	llvm::SLPVectorizerPass::runImpl(llvm::Function&, llvm::ScalarEvolution*, llvm::TargetTransformInfo*, llvm::TargetLibraryInfo*, llvm::AAResults*, llvm::LoopInfo*, llvm::DominatorTree*, llvm::AssumptionCache*, llvm::DemandedBits*, llvm::OptimizationRemarkEmitter*)	
734359	llvm::SLPVectorizerPass::vectorizeSimpleInstructions(llvm::SmallVectorImpl<llvm::Instruction*>&, llvm::BasicBlock*, llvm::slpvectorizer::BoUpSLP&, bool)	
734297	llvm::SLPVectorizerPass::tryToVectorizeList(llvm::ArrayRef<llvm::Value*>, llvm::slpvectorizer::BoUpSLP&, bool)	
651941	llvm::slpvectorizer::BoUpSLP::getTreeCost(llvm::ArrayRef<llvm::Value*>)	
642156	llvm::slpvectorizer::BoUpSLP::getEntryCost(llvm::slpvectorizer::BoUpSLP::TreeEntry const*, llvm::ArrayRef<llvm::Value*>)	
601652	llvm::AArch64TTIImpl::getShuffleCost(llvm::TargetTransformInfo::ShuffleKind, llvm::VectorType*, llvm::ArrayRef<int>, int, llvm::VectorType*, llvm::ArrayRef<llvm::Value*>)	
411262	llvm::TargetLoweringBase::getTypeConversion(llvm::LLVMContext&, llvm::EVT) const	
130463	llvm::EVT::getHalfNumVectorElementsVT(llvm::LLVMContext&) const	
42700	llvm::MVT::getVectorVT(llvm::MVT, unsigned int)	
```
</details>

<details><summary>Backtrace from Xcode 14.2</summary>

```
621274	swift-frontend (61971)	
125651	Main Thread  0x191fba	
125651	start	
125651	swift::mainEntry(int, char const**)	
125649	swift::performFrontend(llvm::ArrayRef<char const*>, char const*, void*, swift::FrontendObserver*)	
125542	performCompileStepsPostSILGen(swift::CompilerInstance&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::PointerUnion<swift::ModuleDecl*, swift::SourceFile*>, swift::PrimarySpecificPaths const&, int&, swift::FrontendObserver*)	
89468	swift::performIRGeneration(swift::ModuleDecl*, swift::IRGenOptions const&, swift::TBDGenOptions const&, std::__1::unique_ptr<swift::SILModule, std::__1::default_delete<swift::SILModule>>, llvm::StringRef, swift::PrimarySpecificPaths const&, llvm::ArrayRef<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>, llvm::GlobalVariable**)	
47492	(anonymous namespace)::LLVMCodeGenThreads::Thread::run()	
47492	swift::performLLVM(swift::IRGenOptions const&, swift::DiagnosticEngine&, llvm::sys::SmartMutex<false>*, llvm::GlobalVariable*, llvm::Module*, llvm::TargetMachine*, llvm::StringRef, swift::UnifiedStatsReporter*)	
32240	llvm::legacy::PassManagerImpl::run(llvm::Module&)	
30223	llvm::FPPassManager::runOnModule(llvm::Module&)	
30215	llvm::FPPassManager::runOnFunction(llvm::Function&)	
28018	llvm::MachineFunctionPass::runOnFunction(llvm::Function&)	
7568	llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&)	
7521	llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&)	
7120	llvm::SelectionDAGISel::CodeGenAndEmitDAG()	
5336	llvm::SelectionDAG::Combine(llvm::CombineLevel, llvm::AAResults*, llvm::CodeGenOpt::Level)	
4258	(anonymous namespace)::DAGCombiner::combine(llvm::SDNode*)	
3874	(anonymous namespace)::DAGCombiner::visit(llvm::SDNode*)	
1715	(anonymous namespace)::DAGCombiner::visitSTORE(llvm::SDNode*)	
825	(anonymous namespace)::DAGCombiner::checkMergeStoreCandidatesForDependencies(llvm::SmallVectorImpl<(anonymous namespace)::DAGCombiner::MemOpLink>&, unsigned int, llvm::SDNode*)	
776	llvm::SDNode::hasPredecessorHelper(llvm::SDNode const*, llvm::SmallPtrSetImpl<llvm::SDNode const*>&, llvm::SmallVectorImpl<llvm::SDNode const*>&, unsigned int, bool)	
566	llvm::SmallPtrSetImplBase::insert_imp_big(void const*)	
225	llvm::SmallPtrSetImplBase::Grow(unsigned int)	
28	_platform_memset	

```
</details>

It looks like `llvm` makes too many optimizations in [SLP Vectorization](https://llvm.org/docs/Vectorizers.html#the-slp-vectorizer). It may be a real issue knowing we have many similar boilerplate enums and switch/case's inside.

So, I was looking for a possibility to disable it somehow. Obviously, it can be done by disabling all the optimizations [-Onone](https://github.com/apple/swift/blob/9268736862ac0bf445ad04995dbf9e5bd40a572e/lib/IRGen/IRGen.cpp#L213) (I even googled something like `-disable-llvm-optzns` exists). However, I took a look at possible passthrough for [llvm options](https://gist.github.com/Kylmakalle/3377b7581cc73b8d0e28e3e2d642372c) in swift, but there was nothing about vectorization we needed.

Luckily, I've found this [llvm PR](https://reviews.llvm.org/D77989), tried the option `-vectorize-slp=false` and it worked! Build traces looks similar in Xcode 14.2 and Xcode 14.3+ now.

P.S. This may worth a write-up to apple/swift or even apple/llvm-project
P.P.S This experience with llvm options may help with #19

**Comment by zintus** [comment]
Amazing findings, thanks for working on this.

**Comment by Kylmakalle** [comment]
With Xcode 15.2 and `indirect` enums, it takes ~150 seconds for the watchOS release build (arm64, arm64_32, armv7k) on M1 Pro. See https://github.com/Swiftgram/TDLibKit/issues/33#issuecomment-2042267357
