### ISSUE TITLE
need detailed explanation of how to install via cocoapods

### ISSUE THREAD

**Issue by Gargo** [Swiftgram/TDLibKit#4]
https://github.com/Swiftgram/TDLibFramework/wiki/CocoaPods-&-Flutter
This url is out of date or describes the steps incompletely. For example there is no "podspec" file in my project and there is no "flutter_additional_ios_build_settings" in my podfile

**Comment by Kylmakalle** [comment]
Point 1. of the guide is for Flutter projects only.

As well as the code
```ruby
### Flutter only <---- as said
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
###
```

You should ignore the step and this part of the code.
Remember to add libz1 and libc++1 as mentioned in a [Readme](https://github.com/Swiftgram/TDLibKit#xcode)

**Comment by Kylmakalle** [comment]
There's also no reason to add this dependency as a Pod cause TDLibkit is supported as SPM module.

**Comment by Gargo** [comment]
@Kylmakalle currently it doesn't work at all

**Comment by Kylmakalle** [comment]
@Gargo please, provide a demo project with Cocoapods that have troubles of connecting TDLibKit
