### ISSUE TITLE
Session logout on all devices

### ISSUE THREAD

**Issue by k0ry** [Swiftgram/TDLibKit#40]
Hello! I'm developing an iOS application using TDLIBKIT. Starting from October 20, 2023, the application kicks the user out of all clients, including the official application. This happens 1-2 minutes after logging into my application. What could be the reason for this behavior? Thanks in advance for your help.

**Comment by k0ry** [comment]
Closing, I discover why that happend. If put empty string as tdlibparameter  systemVersion than telegram system kill all session of the user.

**Comment by Kylmakalle** [comment]
@k0ry I've edited your issue to remove sensitive log-data. From my experience, Telegram servers try to determine untrusted clients based on a wide range of factors, and an empty `system_version` might be one of them. There's nothing else in `setTdlibParameters` than your `api_id`/`api_hash` that can contribute to this "trust system".
If your app is legitimately used as a messenger, you and your users will be fine. 

See https://github.com/tdlib/td/issues/2539

**Comment by Kylmakalle** [comment]
Actually, TDLib will try to determine the `system_version` itself.
https://github.com/tdlib/td/blob/dd77e4628f1a65f332f0cb81c82a19c0fcfa40c2/td/telegram/Td.cpp#L4237
