### ISSUE TITLE
Consideration of privacy issues

### ISSUE THREAD

**Issue by bigface1989** [Swiftgram/TDLibKit#42]
Hello, I really like your application. The built-in translation feature has helped me solve many problems. I would like to know if this software is open source (I am not a computer professional). Are there any security and privacy risks?

**Comment by Kylmakalle** [comment]
👋 Hi. You've opened an issue in TDLibKit, a wrapper of Telegram's [TDLib](https://core.telegram.org/tdlib).

For further questions regarding the Swiftgram app, please, use [the chat](https://t.me/swiftgramchat/448). There're no risks at all.
