### ISSUE TITLE
What's happened with ChatFilterInfo

### ISSUE THREAD

**Issue by k0ry** [Swiftgram/TDLibKit#46]
Hi!
Where is ChatFilterInfo now? And all other routines with chat filters?

I have missed them :)

Thank you!

**Comment by k0ry** [comment]
Folders, off cause :)

**Comment by Kylmakalle** [comment]
@k0ry This API changed eight months ago. It should be called something like `ChatFolder*` now, see https://github.com/Swiftgram/TDLibKit/blob/main/Sources/TDLibKit/Generated/Models/ChatFolder.swift

Here's unofficial visual representation of what changed in schema: https://t.me/tdlibcommits/106
