### ISSUE TITLE
Addressing App Crashes Due to Locked Files in Shared Containers on Background Transition

### ISSUE THREAD

**Issue by sedoyjan** [Swiftgram/TDLibKit#47]
I'm facing a critical issue with my app crashing when it goes into the background, and I'm hoping to find some advice or solutions from this knowledgeable community. My app utilizes a shared directory between itself and a `FileProvider`, alongside `TdLibKit`. 
The logic to work with `TdLibKit` is housed within a shared framework, which necessitates access to certain files by both the App and `FileProvider`.

However, when I minimize the app, it crashes and logs the following error:

```
Terminating with context: <RBSTerminateContext| domain:15 code:0xDEAD10CC explanation:[app<com.sedoyjan.keepgram(74B4C997-E6C2-4B65-8A31-CA1809248B01)>:3941] was suspended with locked system files:
/var/mobile/Containers/Shared/AppGroup/1F13B8D2-EC11-465C-85DE-2ED8797C5DF0/td/db.sqlite
/var/mobile/Containers/Shared/AppGroup/1F13B8D2-EC11-465C-85DE-2ED8797C5DF0/td/td.binlog
not in allowed directories:
/var/mobile/Containers/Data/Application/8C035881-2676-4B92-A9AB-51A664D541C8
/var/mobile/Containers/Data/Application/8C035881-2676-4B92-A9AB-51A664D541C8/tmp reportType:CrashLog maxTerminationResistance:Absolute>
```

If I change sharedDirectory to:
```
let sharedDirectory = try FileManager.default.url(
    for: .documentDirectory,
    in: .userDomainMask,
    appropriateFor: nil,
    create: true
).appending(path: "td").path()
```
then all good

I have already disabled these props:
```
useChatInfoDatabase: false,
useFileDatabase: false,
useMessageDatabase: false,
```

And now it looks like that the only issue is with `td.binlog` file

Is there any way to unlock this file when app goes to background? Or maybe any other solution 🙏 🙏 🙏

**Comment by Kylmakalle** [comment]
For the record: similar issue discussed on the Apple forums https://developer.apple.com/forums/thread/747163?answerId=780826022

**Comment by Kylmakalle** [comment]
@sedoyjan Can you provide more info about your setup and paths you use, share and access from other extensions?

**Comment by Kylmakalle** [comment]
@sedoyjan First of all, are you sure you need to share `databaseDirectory` instead of [filesDirectory](https://github.com/Swiftgram/TDLibKit/blob/68a0cb1c90fecaab55337f7359aa4ae81535493d/Sources/TDLibKit/Generated/Models/SetTdlibParameters.swift#L35)?

Second, it seems like you're doing something wrong with Apple's container-sharing APIs. Perhaps you can describe the use case?

**Comment by SergeiGrigorev** [comment]
@Kylmakalle Hey 👋 
Sorry for delay, regarding database file - well, I'm not sure, but I need to keep session between multiple targets, so I was thinking about to reuse db file from shared dir, but looks like it's a bad idea as it might be locked, maybe you can suggent better idea? 🙏 🙏 🙏

**Comment by sedoyjan** [comment]
@Kylmakalle Hey 👋
Sorry for delay, regarding database file - well, I'm not sure, but I need to keep session between multiple targets, so I was thinking about to reuse db file from shared dir, but looks like it's a bad idea as it might be locked, maybe you can suggent better idea? 🙏 🙏 🙏

**Comment by sedoyjan** [comment]
btw what is stored in `td.binlog`?

**Comment by sedoyjan** [comment]
Looks like it's not an issue, sorry fir disturbing and thanks for replies
