### ISSUE TITLE
Can't compile project Concurrency is only available in iOS 15.0.0 or newer

### ISSUE THREAD

**Issue by sapoepsilon** [Swiftgram/TDLibKit#5]
<img width="798" alt="image" src="https://user-images.githubusercontent.com/47342870/162638370-3d30fa68-ffa8-4026-bdc0-b1fe976842db.png">
After following the instructions on a blank UIKit project, can't build my blank project due to the error above. Any thoughts how to fix it? 

Edit: The error is in TdApi.swift file

**Comment by Kylmakalle** [comment]
Hey, which version of Xcode are you using?

Concurrency backward compatability for iOS 13 arrived in [Xcode 13.2](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_2-release-notes#:~:text=You%20can%20now%20use%20Swift%20Concurrency%20in%20applications%20that%20deploy%20to%20macOS%20Catalina%2010.15%2C%20iOS%2013%2C%20tvOS%2013%2C%20and%20watchOS%206%20or%20newer).

As you can see, CI tests are running fine on 13.2.1 https://github.com/Swiftgram/TDLibKit/runs/5971901455?check_suite_focus=true

**Comment by sapoepsilon** [comment]
@Kylmakalle Thanks, building the project on Xcode 13.2 solved my issue. Oddly enough, at first I was on Xcode 13.3 and wasn't able to build the project whatsoever. Then, I downgraded to 13.1 where concurrency wasn't compatible. I guess, there is a some kind of a bug on Apple's part with the XCode 13.3.

**Comment by happymaskterriblefate** [comment]
Just chiming in here that I also cannot build the project on 13.3. I'm newer to Xcode and iOS dev, but it looks like it's hanging when it hits Animation.swift. It gets here and then never completes.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/80355384/163438593-1cb5e56b-6c36-4285-beee-3a7ee1f9471e.png">

**Comment by happymaskterriblefate** [comment]
Update: per @Kylmakalle's suggestion, downgrading to 13.2 has fixed the hanging issue for me.

**Comment by Kylmakalle** [comment]
Hey @happymaskterriblefate. Unfortunately I can't reproduce your issue with Intel mac and Xcode 13.3 locally. I think you may try Xcode 13.3.1.

Another way is to clear all the basic stuff like DerivedData, SPM cache, then reopen Xcode and try again. Which is pretty common for any iOS development 😄

**Comment by dchudov** [comment]
It seems to be a problem with XCode 13.3.1 while compiling TDLibKit. Had a stuck on 2 different machines even after clean install. Will try to downgrade XCode
https://developer.apple.com/forums/thread/704607

**Comment by Kylmakalle** [comment]
@dchudov @happymaskterriblefate this issue will be tracked in https://github.com/Swiftgram/TDLibKit/issues/7
Thanks for reporting.
