### ISSUE TITLE
Failed to parse JSON object as TDLib request: Unknown class "authenticationCodeInfo"

### ISSUE THREAD

**Issue by wudb** [Swiftgram/TDLibKit#52]
Hi,

I used TDLibKit to create Telegram App, But when I created the client and called login authorization, I failed：
Failed to parse JSON object as TDLib request: Unknown class "authenticationCodeInfo",
please help me, thanks!

The code is as follows:

let query = AuthenticationCodeInfo(nextType: .authenticationCodeTypeSms(AuthenticationCodeTypeSms(length: 6)), phoneNumber: "+8615214217983", timeout: 60, type: .authenticationCodeTypeTelegramMessage(AuthenticationCodeTypeTelegramMessage(length: 6)))

try TGClient.shared.tdClient.send(query: DTO(query))

**Comment by Kylmakalle** [comment]
Make sure you're using up-to-date TDLibKit

**Comment by Kylmakalle** [comment]
You likely have an outdated TDLibFramework. Clean Swift Package Caches and try again.
