### ISSUE TITLE
macOS: Command CodeSign failed with a nonzero exit code

### ISSUE THREAD

**Issue by Roman-Kerimov** [Swiftgram/TDLibKit#54]
<img width="1512" alt="Screenshot 2024-09-09 at 03 10 40" src="https://github.com/user-attachments/assets/245a02a5-6b77-4aa5-b2f0-e045efeb21cf">

**Comment by rokach** [comment]
Same

**Comment by Roman-Kerimov** [comment]
No, I have same issue in Xcode 15.4

Yesterday I mistakenly thought that everything was ok at 15.4

**Comment by rokach** [comment]
Fixed in the new version

**Comment by Kylmakalle** [comment]
During the build of TDLibFramework, macOS part lost the symlink and was improperly produced. Thanks @rokach for checking.
Fixed here https://github.com/Swiftgram/TDLibFramework/commit/72ed1c044a88ae47a13bec35ee3cc05d6b798c61
