### ISSUE TITLE
[workaround available] Build stuck on Apple Silicon with Xcode 13.3+

### ISSUE THREAD

**Issue by Kylmakalle** [Swiftgram/TDLibKit#7]
Unknown bug affects users of TDLibKit. Your build will stuck if you're building with Xcode 13.3(.1) on Apple Silicon. This issue does not affect x86_64 environment (Intel Macs).

May related to this https://developer.apple.com/forums/thread/704607
Will be probably fixed by Apple in further Xcode releases

<img src="https://user-images.githubusercontent.com/24507532/164689698-ef5af1a0-4e00-4bfc-af42-5d8d57d841c0.png" width="400" height="400">

## Workarounds
- Use Apple Rosetta to run your Xcode 13.3+
- Use Xcode 13.2.1. 
If you need to debug iOS 15.4+, you may install proper [DeviceSupport](https://github.com/filsv/iPhoneOSDeviceSupport) files manually.

Seen at https://github.com/Swiftgram/TDLibKit/issues/5#issuecomment-1099416999, https://github.com/Swiftgram/TDLibKit/issues/5#issuecomment-1105822082 and couple more reports in private.

**Comment by dchudov** [comment]
@Kylmakalle Is there any possible option to exclude building TDLibKit framework for armv7 architecture? The whole project is arm64, but embedded SPM did not inherit this rule and it seems it doesn't have its own. It could be a timesaver for a release. Thank you.

**Comment by Kylmakalle** [comment]
@dchudov please file a separate issue
